### ISSUE TITLE
Suggestion: Despawning blocks

### ISSUE THREAD

**Issue by Foreck1** [Laike-Endaril/Controlled-Burn#3]
Hello, first of all. Great mod! I think it could be expanded in scope though, specially for modpack makers:

Could it be possible to add an option for despawning blocks?
Examples:
Remove a torch after 3 in-game days
Slowly destroy scaffolding from various mods
Balance powerful blocks in hardcore packs like the Beacon, anti-mob lanterns
Make machines (by targeting the block or machine when is on) break after time

Preferably an option to add drops when despawning or replacing the block by another would be pretty neat.

If this were to be implemented, this mod would turn into a pretty robust framework for tweaking modpacks.

**Comment by Laike-Endaril** [comment]
Ie. a general-use block tick customization tool, sounds like?  One not directly related to fire blocks, but with more general options for customizing what happens to any block on a random tick?

If so, then that's outside the scope of this mod, though I agree it's a good idea for a new mod.  This mod specifically alters the fire block itself (and no other blocks), whereas what I think you're suggesting would be a global system that triggers on any random block tick, filters by block, and then applies any new behaviors specified.

Unfortunately, I can't take on any new projects right now...I'm too busy with a certain suite of indev mods that I've been working on for a while, and this idea seems like it could expand pretty far and thus take a lot of development time.

I'm closing this specifically because I don't think it would be done *as part of Controlled Burn*, but I will still see and read any responses here even with it "closed".

**Comment by Foreck1** [comment]
Thanks for the consideration, it seems indeed that my proposal is outside of the scope of your mod. If there's nothing more that can be said for the time being, so I wish you luck on your other projects.
