### ISSUE TITLE
Hello, can I count on support for new versions of minecraft? (1.15)

### ISSUE THREAD

**Issue by gekkone** [Laike-Endaril/Controlled-Burn#4]

**Comment by Laike-Endaril** [comment]
Hey, sorry, but for now I'm developing for 1.12.2 only; I simply have my hands too full with other stuff.

In particular, I'm part of a modpack team, and concentrating on what they need, which is why I haven't been as active on my existing mods.

If you're *particularly* interested in the featureset, you're free to port it, or to reference the code and make something similar.  My policy in that regard is "you're free to port/copy it and release your result, but if I do my own separate port later, don't get mad" (I would not ask anyone to take down or discontinue any ports/projects based on my own though)
